Repository thoth-station/cleanup-job, pull requests merged in 2018-08, with the labels that each got.

#38 Automatic update of dependency thoth-common from 0.2.1 to 0.2.2
  Pipfile.lock
Labels: bot

#41 Added zuul config
  .zuul.yaml
Labels: approved, size/S

#45 Do not use bare except
  app.py
Labels: approved, size/XS

#44 Add metadata to job template
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#49 Automatic update of dependency thoth-common from 0.2.2 to 0.2.3
  Pipfile.lock
Labels: bot

#51 Automatic update of dependency thoth-common from 0.2.3 to 0.2.4
  Pipfile.lock
Labels: bot

#52 Automatic update of dependency thoth-common from 0.2.4 to 0.2.5
  Pipfile.lock
Labels: bot

#50 added a build trigger
  .zuul.yaml
Labels: size/S, size/XS
