Repository thoth-station/cleanup-job, pull requests merged in 2018-07, with the labels that each got.

#21 Automatic update of dependency requests from 2.18.4 to 2.19.1
  Pipfile.lock
Labels: approved, bot, size/S

#23 Use service account token function from thoth-common
  app.py
Labels: approved, size/S

#24 Automatic update of dependency thoth-common from 0.0.9 to 0.1.0
  Pipfile.lock
Labels: bot

#32 Initial dependency lock
  Pipfile.lock
Labels: bot

#34 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#35 Add CronJob suspend configuration
  openshift/cronJob-template.yaml
Labels: approved
