Repository thoth-station/cleanup-job, pull requests merged in 2018-04, with the labels that each got.

#5 Fix image name
  openshift/buildConfig-template.yaml
Labels: approved

#4 Remove old dockerfile files
  Dockerfile
  build.sh
  requirements.txt
Labels: approved

#6 adding the OWNERS file
  OWNERS
Labels: approved, size/XS

#8 Separate imagestreams
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/L

#10 Use a separator in URL only once
  app.py
Labels: approved

#9 Expand namespace from configmap
  openshift/cronJob-template.yaml
Labels: approved, size/XS
