Repository thoth-station/cleanup-job, pull requests merged in 2018-06, with the labels that each got.

#17 Rename THOTH_MIDDLEEND_NAMESPACE to THOTH_MIDDLETIER_NAMESPACE
  app.py
  openshift/cronJob-template.yaml
Labels: approved, lgtm, size/XS

#18 set resource limits of BC, DC; relocked Pipfile
  Pipfile.lock
  openshift/buildConfig-template.yaml
Labels: approved, size/S

#19 Forbid concurrent cleanup jobs
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#20 Do not use configmap for logging configuration
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#22 Automatic update of dependency thoth-common from 0.0.6 to 0.0.9
  Pipfile.lock
Labels: approved, bot, size/M
