Repository thoth-station/cleanup-job, pull requests merged in 2019-06, with the labels that each got.

#163 Automatic update of dependency thoth-common from 0.8.7 to 0.8.11
  Pipfile.lock
Labels: bot

#164 Automatic update of dependency prometheus-client from 0.6.0 to 0.7.0
  Pipfile.lock
Labels: bot

#166 Run cleanup job every 2 hours
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#167 Update zuul pipeline to use the new version trigger build job
  .zuul.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#168 Increase resources so cleanups are not OOM killed
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#171 Downgrade prometheus-client to fix bug in the latest release
  Pipfile
  Pipfile.lock
Labels: approved, size/S

#173 Automatic update of dependency openshift from 0.8.9 to 0.9.0
  Pipfile.lock
Labels: bot

#174 Automatic update of dependency kubernetes from 8.0.1 to 9.0.0
  Pipfile.lock
Labels: bot

#172 Standardize environment variables
  app.py
  openshift/cronJob-template.yaml
Labels: approved, size/S

#175 Automatic update of dependency thoth-common from 0.8.11 to 0.9.0
  Pipfile.lock
Labels: bot

#176 Port cleanup job to use thoth-common
  app.py
Labels: approved, size/XS

#178 Fix gathering TTL from objects
  app.py
Labels: approved, size/XS

#179 Delete also pods as they stay in the cluster once we delete jobs
  app.py
Labels: approved, size/XS

#169 Configure starting deadline seconds to large number
  openshift/cronJob-template.yaml
Labels: size/XS

#177 Fix Prometheus reporting related issues
  app.py
Labels: approved, size/M, size/S

#180 Fix too many values to unpack error
  app.py
Labels: approved, size/XS

#181 Automatic update of dependency thoth-common from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot

#182 Document local usage
  README.rst
Labels: approved, size/S

#183 Modify metrics
  app.py
Labels: approved, size/M
