Repository thoth-station/cleanup-job, pull requests merged in 2019-03, with the labels that each got.

#142 reworked the service account part
  .zuul.yaml
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/L

#143 fixed a missing dollar sign in one of the openshift templates
  openshift/cronJob-template.yaml
Labels: size/XS

#144 Automatic update of dependency thoth-common from 0.7.1 to 0.8.0
  Pipfile.lock
Labels: bot

#145 Automatic update of dependency thoth-common from 0.8.0 to 0.8.1
  Pipfile.lock
Labels: bot

#147 Add Thoth's configuration file
  .thoth.yaml
Labels: size/S

#148 Automatic update of dependency openshift from 0.8.6 to 0.8.7
  Pipfile.lock
Labels: bot
