Repository thoth-station/cleanup-job, pull requests merged in 2019-09, with the labels that each got.

#199 WIP: Check resource state before deletion
  app.py
Labels: approved, size/L, work-in-progress

#196 Start using Thoth's base image
  .s2i/bin/assemble
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#200 Propagate deployment name for sentry environment
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#201 Automatic update of dependency thoth-common from 0.9.8 to 0.9.9
  Pipfile.lock
Labels: bot

#202 Automatic update of dependency thoth-common from 0.9.9 to 0.9.10
  Pipfile.lock
Labels: bot

#203 Provide default registry value in template
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#205 Run the cronjob each 10 minutes
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#204 Lower cronjob requirements
  openshift/cronJob-template.yaml
Labels: approved, human_intervention_required, needs-rebase, size/XS
