Repository thoth-station/cleanup-job, pull requests merged in 2019-08, with the labels that each got.

#189 Automatic update of dependency thoth-common from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#190 Start using Thoth in OpenShift's s2i
  .s2i/bin/assemble
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: size/M

#191 Automatic update of dependency kubernetes from 9.0.0 to 9.0.1
  Pipfile.lock
Labels: bot

#194 Initial dependency lock
  Pipfile.lock
Labels: bot, size/L

#195 Added config
  .thoth.yaml
Labels: approved, size/S
