Repository thoth-station/cleanup-job, pull requests merged in 2019-12, with the labels that each got.

#230 Automatic update of dependency thoth-common from 0.9.19 to 0.9.20
  Pipfile.lock
Labels: bot, size/M

#231 Automatic update of dependency thoth-common from 0.9.20 to 0.9.21
  Pipfile.lock
Labels: bot, size/XS

#233 Update Thoth configuration file and Thoth's s2i configuration
  .thoth.yaml
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#234 Automatic update of dependency openshift from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/S

#235 Automatic update of dependency thoth-common from 0.9.21 to 0.9.22
  Pipfile.lock
Labels: bot, size/XS
