Repository thoth-station/cleanup-job, pull requests merged in 2019-11, with the labels that each got.

#213 Automatic update of dependency python-dateutil from 2.8.0 to 2.8.1
  Pipfile.lock
Labels: bot

#215 Lower cleanup TTL to 2 hours by default
  README.rst
  app.py
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#214 Stop using starting deadline seconds
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#218 update condition based upon job json to enable job cleanup
  app.py
  pyproject.toml
Labels: approved, size/S

#219 Automatic update of dependency thoth-common from 0.9.14 to 0.9.15
  Pipfile.lock
Labels: bot

#220 Automatic update of dependency thoth-common from 0.9.15 to 0.9.16
  Pipfile.lock
Labels: bot, size/S

#221 Lower TTL to 10 minutes
  README.rst
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#223 Do not delete pods
  app.py
Labels: approved, size/XS

#224 Add liveness probe
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#225 Automatic update of dependency openshift from 0.8.0 to 0.10.0
  Pipfile.lock
Labels: bot, size/L

#226 Automatic update of dependency kubernetes from 8.0.2 to 10.0.1
  Pipfile.lock
Labels: bot, size/XS

#228 Automatic update of dependency thoth-common from 0.9.16 to 0.9.18
  Pipfile.lock
Labels: bot, size/XS

#229 Automatic update of dependency thoth-common from 0.9.18 to 0.9.19
  Pipfile.lock
Labels: bot, size/XS
