Repository thoth-station/cleanup-job, pull requests merged in 2019-02, with the labels that each got.

#129 Automatic update of dependency python-dateutil from 2.7.5 to 2.8.0
  Pipfile.lock
Labels: bot

#130 Automatic update of dependency openshift from 0.8.4 to 0.8.5
  Pipfile.lock
Labels: bot

#132 Automatic update of dependency thoth-common from 0.6.0 to 0.7.1
  Pipfile.lock
Labels: bot

#133 Automatic update of dependency openshift from 0.8.5 to 0.8.6
  Pipfile.lock
Labels: bot

#134 Automatic update of dependency prometheus-client from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot

#137 Add prometheus configuration
  openshift/cronJob-template.yaml
Labels: size/S

#138 Revert "Automatic update of dependency prometheus-client from 0.5.0 to 0.6.0"
  Pipfile.lock
Labels: size/M

#139 Automatic update of dependency prometheus-client from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot
