Repository thoth-station/cleanup-job, pull requests merged in 2020-06, with the labels that each got.

#296 Clean up old Argo workflows
  app.py
Labels: approved, size/M

#300 Release of version 0.8.1
  CHANGELOG.md
  version.py
Labels: bot, size/L

#302 Automatic update of dependency thoth-common from 0.13.8 to 0.13.13
  Pipfile.lock
Labels: approved, bot
