Repository thoth-station/cleanup-job, pull requests merged in 2020-04, with the labels that each got.

#279 updated openshift and kubernetes for consistency
  Pipfile
Labels: approved

#280 Initial dependency lock
  Pipfile.lock
Labels: bot

#281 Automatic update of dependency thoth-common from 0.12.5 to 0.12.6
  Pipfile.lock
Labels: bot, size/XS

#282 Automatic update of dependency thoth-common from 0.12.6 to 0.12.7
  Pipfile.lock
Labels: bot, size/S

#283 Automatic update of dependency thoth-common from 0.12.7 to 0.12.8
  Pipfile.lock
Labels: bot, size/S

#284 Automatic update of dependency thoth-common from 0.12.8 to 0.12.9
  Pipfile.lock
Labels: bot, size/XS

#285 Automatic update of dependency thoth-common from 0.12.9 to 0.12.10
  Pipfile.lock
Labels: bot, size/S

#286 Automatic update of dependency thoth-common from 0.12.10 to 0.13.0
  Pipfile.lock
Labels: bot, size/XS

#287 Automatic update of dependency click from 7.1.1 to 7.1.2
  Pipfile.lock
Labels: bot, size/XS

#288 Automatic update of dependency thoth-common from 0.13.0 to 0.13.1
  Pipfile.lock
Labels: bot, size/XS

#289 Automatic update of dependency thoth-common from 0.13.1 to 0.13.2
  Pipfile.lock
Labels: bot, size/S
