Repository thoth-station/cleanup-job, pull requests merged in 2020-01, with the labels that each got.

#239 Do not run adviser from bc in debug mode
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#238 Automatic update of dependency thoth-common from 0.9.22 to 0.9.23
  Pipfile.lock
Labels: bot, size/M

#240 Automatic update of dependency thoth-common from 0.9.23 to 0.9.24
  Pipfile.lock
Labels: bot, size/S

#241 Automatic update of dependency thoth-common from 0.9.24 to 0.9.25
  Pipfile.lock
Labels: bot, size/XS

#242 Automatic update of dependency thoth-common from 0.9.25 to 0.9.26
  Pipfile.lock
Labels: bot, size/XS

#243 Delete long-living workload pods once jobs are deleted
  app.py
Labels: approved, size/XS

#237 Happy new year!
  app.py
Labels: approved, size/XS

#244 Automatic update of dependency thoth-common from 0.9.26 to 0.9.27
  Pipfile.lock
Labels: bot, size/M

#245 Automatic update of dependency thoth-common from 0.9.27 to 0.9.28
  Pipfile.lock
Labels: bot, size/XS

#246 Automatic update of dependency thoth-common from 0.9.28 to 0.9.29
  Pipfile.lock
Labels: bot, size/XS

#247 Automatic update of dependency thoth-common from 0.9.29 to 0.9.30
  Pipfile.lock
Labels: bot, size/M

#248 Automatic update of dependency thoth-common from 0.9.30 to 0.9.31
  Pipfile.lock
Labels: bot, size/XS

#249 Automatic update of dependency thoth-common from 0.9.31 to 0.10.0
  Pipfile.lock
Labels: bot, size/S

#250 Log resource that is about to be cleaned up
  app.py
Labels: approved, size/XS

#251 Automatic update of dependency thoth-common from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/S
