Repository thoth-station/cleanup-job, pull requests merged in 2020-02, with the labels that each got.

#252 Automatic update of dependency thoth-common from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: bot, size/XS

#253 Rewrite clean up to properly handle image streams
  app.py
Labels: approved, size/L

#254 Automatic update of dependency thoth-common from 0.10.2 to 0.10.3
  Pipfile.lock
Labels: bot, size/S

#255 Automatic update of dependency thoth-common from 0.10.3 to 0.10.4
  Pipfile.lock
Labels: bot, size/XS

#256 Automatic update of dependency thoth-common from 0.10.4 to 0.10.5
  Pipfile.lock
Labels: bot, size/S

#257 Increase memory requests needed for cronjob
  openshift/cronJob-template.yaml
Labels: approved, size/S

#258 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#259 Automatic update of dependency thoth-common from 0.10.5 to 0.10.6
  Pipfile.lock
Labels: bot, size/S

#260 Automatic update of dependency thoth-common from 0.10.6 to 0.10.7
  Pipfile.lock
Labels: bot, size/S

#261 Automatic update of dependency openshift from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: bot, size/S

#262 Automatic update of dependency thoth-common from 0.10.7 to 0.10.8
  Pipfile.lock
Labels: bot, size/S

#263 Automatic update of dependency thoth-common from 0.10.8 to 0.10.9
  Pipfile.lock
Labels: bot, size/S
